[project]
name = "kafka-pub-sub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "kafka-python>=2.2.15",
    "ruff>=0.12.11",
]
